# Generated by Django 5.0.14 on 2025-07-20 14:24

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Party Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('room_code', models.CharField(max_length=10, unique=True, verbose_name='Room Code')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='private', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Max Participants')),
                ('require_approval', models.BooleanField(default=False, verbose_name='Require Host Approval')),
                ('allow_chat', models.BooleanField(default=True, verbose_name='Allow Chat')),
                ('allow_reactions', models.BooleanField(default=True, verbose_name='Allow Reactions')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Start Time')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Actually Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('current_timestamp', models.DurationField(default=datetime.timedelta(0), verbose_name='Current Video Position')),
                ('is_playing', models.BooleanField(default=False, verbose_name='Is Playing')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='Last Sync Update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='videos.video')),
            ],
            options={
                'verbose_name': 'Watch Party',
                'verbose_name_plural': 'Watch Parties',
                'db_table': 'watch_parties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('inappropriate_chat', 'Inappropriate Chat'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(verbose_name='Report Description')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_in_parties', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_reports', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='parties.watchparty')),
            ],
            options={
                'verbose_name': 'Party Report',
                'verbose_name_plural': 'Party Reports',
                'db_table': 'party_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Surprise'), ('😢', 'Sad'), ('😡', 'Angry'), ('👏', 'Clap'), ('🔥', 'Fire'), ('⚽', 'Football'), ('🎉', 'Party'), ('👍', 'Thumbs Up')], max_length=10)),
                ('video_timestamp', models.DurationField(verbose_name='Video Position When Reacted')),
                ('x_position', models.FloatField(default=0.5)),
                ('y_position', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_reactions', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='parties.watchparty')),
            ],
            options={
                'verbose_name': 'Party Reaction',
                'verbose_name_plural': 'Party Reactions',
                'db_table': 'party_reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('moderator', 'Moderator'), ('host', 'Host')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('kicked', 'Kicked'), ('left', 'Left')], default='approved', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_participations', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='parties.watchparty')),
            ],
            options={
                'verbose_name': 'Party Participant',
                'verbose_name_plural': 'Party Participants',
                'db_table': 'party_participants',
                'unique_together': {('party', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PartyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Invitation Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(verbose_name='Invitation Expires At')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='parties.watchparty')),
            ],
            options={
                'verbose_name': 'Party Invitation',
                'verbose_name_plural': 'Party Invitations',
                'db_table': 'party_invitations',
                'ordering': ['-created_at'],
                'unique_together': {('party', 'invitee')},
            },
        ),
    ]
