# Generated by Django 5.0.14 on 2025-07-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0001_initial"),
        ("videos", "0002_video_gdrive_download_url_video_gdrive_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="gdrive_file_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Google Drive File ID"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="movie_duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Movie Duration"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="movie_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Movie Title"
            ),
        ),
        migrations.AlterField(
            model_name="watchparty",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="videos.video",
            ),
        ),
    ]
