# Generated by Django 5.0.14 on 2025-07-24 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parties",
            "0002_watchparty_gdrive_file_id_watchparty_movie_duration_and_more",
        ),
        ("videos", "0003_videoprocessing_videostreamingurl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="allow_join_by_code",
            field=models.BooleanField(
                default=True, verbose_name="Allow Join by Room Code"
            ),
        ),
        migrations.AddIndex(
            model_name="watchparty",
            index=models.Index(
                fields=["status", "created_at"], name="watch_parti_status_c9c8ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchparty",
            index=models.Index(
                fields=["host", "status"], name="watch_parti_host_id_b71d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchparty",
            index=models.Index(
                fields=["visibility", "status"], name="watch_parti_visibil_537c7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchparty",
            index=models.Index(
                fields=["scheduled_start"], name="watch_parti_schedul_fcded2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchparty",
            index=models.Index(
                fields=["room_code"], name="watch_parti_room_co_4a6d84_idx"
            ),
        ),
    ]
