# Generated by Django 5.0.14 on 2025-07-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0003_watchparty_allow_join_by_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="allow_public_search",
            field=models.BooleanField(
                default=True, verbose_name="Allow in Public Search"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="invite_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                unique=True,
                verbose_name="Shareable Invite Code",
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="invite_code_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Invite Code Expiry"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="peak_concurrent_viewers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Peak Concurrent Viewers"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="total_chat_messages",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Chat Messages"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="total_reactions",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Reactions"
            ),
        ),
        migrations.AddField(
            model_name="watchparty",
            name="total_viewers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Unique Viewers"
            ),
        ),
        migrations.CreateModel(
            name="PartyEngagementAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_watch_time", models.DurationField(blank=True, null=True)),
                (
                    "bounce_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage who left within first 5 minutes",
                    ),
                ),
                (
                    "engagement_score",
                    models.FloatField(
                        default=0.0, help_text="Overall engagement score 0-100"
                    ),
                ),
                ("most_rewound_timestamp", models.DurationField(blank=True, null=True)),
                ("most_paused_timestamp", models.DurationField(blank=True, null=True)),
                (
                    "reaction_hotspots",
                    models.JSONField(
                        default=list, help_text="Timestamps with high reaction activity"
                    ),
                ),
                ("chat_activity_score", models.FloatField(default=0.0)),
                ("user_retention_rate", models.FloatField(default=0.0)),
                ("invitation_conversion_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_analytics",
                        to="parties.watchparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Party Engagement Analytics",
                "verbose_name_plural": "Party Engagement Analytics",
                "db_table": "party_engagement_analytics",
            },
        ),
    ]
