# Generated by Django 5.0.14 on 2025-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="gdrive_download_url",
            field=models.URLField(blank=True, verbose_name="Google Drive Download URL"),
        ),
        migrations.AddField(
            model_name="video",
            name="gdrive_file_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Google Drive File ID"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="gdrive_mime_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Google Drive MIME Type"
            ),
        ),
    ]
