# Generated by Django 5.0.14 on 2025-07-20 14:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_registered_users', models.PositiveIntegerField(default=0)),
                ('active_users_today', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('premium_users', models.PositiveIntegerField(default=0)),
                ('total_videos', models.PositiveIntegerField(default=0)),
                ('videos_uploaded_today', models.PositiveIntegerField(default=0)),
                ('total_parties', models.PositiveIntegerField(default=0)),
                ('parties_created_today', models.PositiveIntegerField(default=0)),
                ('total_watch_time_hours', models.FloatField(default=0.0)),
                ('total_chat_messages', models.PositiveIntegerField(default=0)),
                ('total_reactions', models.PositiveIntegerField(default=0)),
                ('average_load_time_seconds', models.FloatField(default=0.0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('total_storage_gb', models.FloatField(default=0.0)),
                ('bandwidth_used_gb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'db_table': 'system_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PartyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_viewers', models.PositiveIntegerField(default=0, verbose_name='Total Unique Viewers')),
                ('peak_concurrent_viewers', models.PositiveIntegerField(default=0, verbose_name='Peak Concurrent Viewers')),
                ('average_viewers', models.FloatField(default=0.0, verbose_name='Average Concurrent Viewers')),
                ('total_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Total Duration (minutes)')),
                ('actual_watch_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Actual Watch Duration (minutes)')),
                ('pause_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Total Pause Time (minutes)')),
                ('total_chat_messages', models.PositiveIntegerField(default=0, verbose_name='Total Chat Messages')),
                ('total_reactions', models.PositiveIntegerField(default=0, verbose_name='Total Reactions')),
                ('average_messages_per_viewer', models.FloatField(default=0.0, verbose_name='Average Messages Per Viewer')),
                ('total_joins', models.PositiveIntegerField(default=0, verbose_name='Total Joins')),
                ('total_leaves', models.PositiveIntegerField(default=0, verbose_name='Total Leaves')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Completion Rate (%)')),
                ('buffering_events', models.PositiveIntegerField(default=0, verbose_name='Total Buffering Events')),
                ('sync_issues', models.PositiveIntegerField(default=0, verbose_name='Synchronization Issues')),
                ('technical_problems', models.PositiveIntegerField(default=0, verbose_name='Technical Problems Reported')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='parties.watchparty')),
            ],
            options={
                'verbose_name': 'Party Analytics',
                'verbose_name_plural': 'Party Analytics',
                'db_table': 'party_analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_watch_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Total Watch Time (minutes)')),
                ('this_week_watch_time_minutes', models.PositiveIntegerField(default=0, verbose_name='This Week Watch Time (minutes)')),
                ('this_month_watch_time_minutes', models.PositiveIntegerField(default=0, verbose_name='This Month Watch Time (minutes)')),
                ('total_parties_joined', models.PositiveIntegerField(default=0, verbose_name='Total Parties Joined')),
                ('total_parties_hosted', models.PositiveIntegerField(default=0, verbose_name='Total Parties Hosted')),
                ('this_week_parties_joined', models.PositiveIntegerField(default=0, verbose_name='This Week Parties Joined')),
                ('this_month_parties_joined', models.PositiveIntegerField(default=0, verbose_name='This Month Parties Joined')),
                ('total_messages_sent', models.PositiveIntegerField(default=0, verbose_name='Total Messages Sent')),
                ('this_week_messages_sent', models.PositiveIntegerField(default=0, verbose_name='This Week Messages Sent')),
                ('this_month_messages_sent', models.PositiveIntegerField(default=0, verbose_name='This Month Messages Sent')),
                ('videos_uploaded', models.PositiveIntegerField(default=0, verbose_name='Videos Uploaded')),
                ('reactions_sent', models.PositiveIntegerField(default=0, verbose_name='Reactions Sent')),
                ('friends_added', models.PositiveIntegerField(default=0, verbose_name='Friends Added')),
                ('average_session_duration_minutes', models.FloatField(default=0.0, verbose_name='Average Session Duration (minutes)')),
                ('favorite_genre', models.CharField(blank=True, max_length=100, verbose_name='Favorite Genre')),
                ('most_active_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Most Active Hour (0-23)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics',
                'verbose_name_plural': 'User Analytics',
                'db_table': 'user_analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view_start', 'Video View Started'), ('view_end', 'Video View Ended'), ('party_join', 'Party Joined'), ('party_leave', 'Party Left'), ('chat_message', 'Chat Message Sent'), ('reaction_sent', 'Reaction Sent'), ('video_upload', 'Video Uploaded'), ('friend_request', 'Friend Request Sent'), ('buffering', 'Video Buffering'), ('quality_change', 'Quality Changed'), ('sync_issue', 'Synchronization Issue'), ('error_occurred', 'Error Occurred')], max_length=50)),
                ('event_data', models.JSONField(default=dict, verbose_name='Event Data')),
                ('session_id', models.CharField(max_length=100, verbose_name='Session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Timestamp')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Event Duration')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='parties.watchparty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='videos.video')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_e_user_id_4d513c_idx'), models.Index(fields=['party', 'timestamp'], name='analytics_e_party_i_594650_idx'), models.Index(fields=['video', 'timestamp'], name='analytics_e_video_i_e8069b_idx'), models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_5b2eb4_idx'), models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total Views')),
                ('unique_viewers', models.PositiveIntegerField(default=0, verbose_name='Unique Viewers')),
                ('this_week_views', models.PositiveIntegerField(default=0, verbose_name='This Week Views')),
                ('this_month_views', models.PositiveIntegerField(default=0, verbose_name='This Month Views')),
                ('total_watch_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Total Watch Time (minutes)')),
                ('average_watch_duration', models.FloatField(default=0.0, verbose_name='Average Watch Duration (%)')),
                ('completion_rate', models.FloatField(default=0.0, verbose_name='Completion Rate (%)')),
                ('total_parties_created', models.PositiveIntegerField(default=0, verbose_name='Total Parties Created')),
                ('total_reactions', models.PositiveIntegerField(default=0, verbose_name='Total Reactions')),
                ('total_comments', models.PositiveIntegerField(default=0, verbose_name='Total Comments')),
                ('common_skip_start_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Common Skip Start (seconds)')),
                ('common_skip_end_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Common Skip End (seconds)')),
                ('most_rewatched_start_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Most Rewatched Start (seconds)')),
                ('most_rewatched_end_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Most Rewatched End (seconds)')),
                ('average_quality_selected', models.CharField(blank=True, max_length=10, verbose_name='Average Quality Selected')),
                ('buffering_rate', models.FloatField(default=0.0, verbose_name='Buffering Rate (%)')),
                ('loading_time_seconds', models.FloatField(default=0.0, verbose_name='Average Loading Time (seconds)')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Average Rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='Total Ratings')),
                ('thumbs_up', models.PositiveIntegerField(default=0, verbose_name='Thumbs Up')),
                ('thumbs_down', models.PositiveIntegerField(default=0, verbose_name='Thumbs Down')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Analytics',
                'verbose_name_plural': 'Video Analytics',
                'db_table': 'video_analytics',
                'indexes': [models.Index(fields=['total_views'], name='video_analy_total_v_12e77d_idx'), models.Index(fields=['unique_viewers'], name='video_analy_unique__f9204c_idx'), models.Index(fields=['average_rating'], name='video_analy_average_e3bc1a_idx')],
            },
        ),
    ]
