# Generated by Django 5.0.14 on 2025-07-23 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        (
            "parties",
            "0002_watchparty_gdrive_file_id_watchparty_movie_duration_and_more",
        ),
        ("videos", "0002_video_gdrive_download_url_video_gdrive_file_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Session ID"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Session Start Time")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Session End Time"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Device Type"
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="Browser"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Operating System"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="WatchTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_watch_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Watch Time (seconds)"
                    ),
                ),
                (
                    "last_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Last Position (seconds)"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0, verbose_name="Completion Percentage"
                    ),
                ),
                (
                    "average_quality",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Average Quality"
                    ),
                ),
                (
                    "buffering_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Buffering Events"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Watch Time",
                "verbose_name_plural": "Watch Times",
                "db_table": "watch_times",
            },
        ),
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="analytics_e_party_i_594650_idx",
        ),
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="analytics_e_video_i_e8069b_idx",
        ),
        migrations.RenameField(
            model_name="partyanalytics",
            old_name="total_chat_messages",
            new_name="total_messages",
        ),
        migrations.RemoveField(
            model_name="analyticsevent",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="analyticsevent",
            name="party",
        ),
        migrations.RemoveField(
            model_name="analyticsevent",
            name="video",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="actual_watch_duration_minutes",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="average_messages_per_viewer",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="average_viewers",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="completion_rate",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="pause_time_minutes",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="peak_concurrent_viewers",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="technical_problems",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="total_duration_minutes",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="total_joins",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="total_leaves",
        ),
        migrations.RemoveField(
            model_name="partyanalytics",
            name="total_viewers",
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
        migrations.AddField(
            model_name="partyanalytics",
            name="avg_session_duration",
            field=models.FloatField(
                default=0.0, verbose_name="Average Session Duration (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="partyanalytics",
            name="peak_concurrent_participants",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Peak Concurrent Participants"
            ),
        ),
        migrations.AddField(
            model_name="partyanalytics",
            name="total_participants",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total Participants"
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("video_play", "Video Play"),
                    ("video_pause", "Video Pause"),
                    ("video_seek", "Video Seek"),
                    ("party_join", "Party Join"),
                    ("party_leave", "Party Leave"),
                    ("chat_message", "Chat Message"),
                    ("reaction_sent", "Reaction Sent"),
                    ("user_login", "User Login"),
                    ("user_logout", "User Logout"),
                    ("video_upload", "Video Upload"),
                    ("party_create", "Party Create"),
                    ("buffering", "Video Buffering"),
                    ("error", "Error Occurred"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Session ID"
            ),
        ),
        migrations.AlterField(
            model_name="partyanalytics",
            name="buffering_events",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Buffering Events"
            ),
        ),
        migrations.AlterField(
            model_name="partyanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="partyanalytics",
            name="sync_issues",
            field=models.PositiveIntegerField(default=0, verbose_name="Sync Issues"),
        ),
        migrations.AlterField(
            model_name="partyanalytics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["processed", "timestamp"], name="analytics_e_process_c64512_idx"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="watchtime",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_times",
                to="parties.watchparty",
            ),
        ),
        migrations.AddField(
            model_name="watchtime",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_times",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="watchtime",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_times",
                to="videos.video",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "start_time"], name="user_sessio_user_id_c66047_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_id"], name="user_sessio_session_e62ba3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchtime",
            index=models.Index(
                fields=["user", "created_at"], name="watch_times_user_id_cf7a6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchtime",
            index=models.Index(
                fields=["video", "created_at"], name="watch_times_video_i_b82c5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchtime",
            index=models.Index(
                fields=["party", "created_at"], name="watch_times_party_i_5cf0a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchtime",
            unique_together={("user", "video", "party")},
        ),
    ]
