# Generated by Django 5.0.14 on 2025-09-24 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_usersession_watchtime_and_more"),
        ("parties", "0004_watchparty_allow_public_search_and_more"),
        ("videos", "0003_videoprocessing_videostreamingurl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Event Duration"
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="parties.watchparty",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_events",
                to="videos.video",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["party", "timestamp"], name="analytics_e_party_i_594650_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["video", "timestamp"], name="analytics_e_video_i_e8069b_idx"
            ),
        ),
    ]
