# Generated by Django 5.0.14 on 2025-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_drive_connected",
            field=models.BooleanField(
                default=False, verbose_name="Google Drive Connected"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_drive_folder_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Google Drive Folder ID"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_drive_refresh_token",
            field=models.TextField(
                blank=True, verbose_name="Google Drive Refresh Token"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_drive_token",
            field=models.TextField(
                blank=True, verbose_name="Google Drive Access Token"
            ),
        ),
    ]
