# Generated by Django 5.0.14 on 2025-07-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_google_drive_connected_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
