# Generated by Django 5.0.14 on 2025-07-24 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_update_user_model_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=32, verbose_name="Secret Key"),
                ),
                (
                    "backup_codes",
                    models.JSONField(default=list, verbose_name="Backup Codes"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="2FA Enabled"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two-Factor Authentication",
                "verbose_name_plural": "Two-Factor Authentications",
                "db_table": "two_factor_auth",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "refresh_token_hash",
                    models.CharField(max_length=255, verbose_name="Refresh Token Hash"),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="Device Information"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "auth_user_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="auth_user_s_user_id_e0ab05_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="auth_user_s_expires_3df8ae_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="auth_user_s_created_115f57_idx"
                    ),
                ],
            },
        ),
    ]
