# Generated by Django 5.0.14 on 2025-07-27 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_add_social_auth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience_points",
            field=models.IntegerField(default=0, verbose_name="Experience Points"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Online Status"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Activity"),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1, verbose_name="User Level"),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False, verbose_name="Onboarding Completed"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_watch_time",
            field=models.DurationField(
                default=datetime.timedelta(0), verbose_name="Total Watch Time"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="virtual_currency",
            field=models.IntegerField(default=0, verbose_name="Virtual Currency"),
        ),
    ]
