# Generated by Django 5.0.14 on 2025-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0007_alter_user_groups_alter_user_user_permissions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="google_drive_token_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Google Drive Token Expiry"
            ),
        ),
    ]
