# Generated by Django 5.0.14 on 2025-07-24 22:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Email Notifications"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push Notifications"
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False, verbose_name="SMS Notifications"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, verbose_name="In-App Notifications"
                    ),
                ),
                (
                    "party_invites",
                    models.BooleanField(default=True, verbose_name="Party Invitations"),
                ),
                (
                    "party_updates",
                    models.BooleanField(default=True, verbose_name="Party Updates"),
                ),
                (
                    "friend_requests",
                    models.BooleanField(default=True, verbose_name="Friend Requests"),
                ),
                (
                    "video_uploads",
                    models.BooleanField(
                        default=True, verbose_name="Video Upload Notifications"
                    ),
                ),
                (
                    "system_updates",
                    models.BooleanField(default=True, verbose_name="System Updates"),
                ),
                (
                    "marketing",
                    models.BooleanField(
                        default=False, verbose_name="Marketing Communications"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Enable Quiet Hours"
                    ),
                ),
                (
                    "quiet_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet Start Time"
                    ),
                ),
                (
                    "quiet_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Quiet End Time"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
                "db_table": "notification_channels",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(verbose_name="Push Endpoint")),
                ("p256dh_key", models.TextField(verbose_name="P256DH Key")),
                ("auth_key", models.TextField(verbose_name="Auth Key")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web Browser"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("desktop", "Desktop"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Device Name"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("fcm_token", models.TextField(blank=True, verbose_name="FCM Token")),
                ("apns_token", models.TextField(blank=True, verbose_name="APNS Token")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Last Used"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "db_table": "push_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="push_subscr_user_id_c81a15_idx",
                    ),
                    models.Index(
                        fields=["platform", "is_active"],
                        name="push_subscr_platfor_832a78_idx",
                    ),
                ],
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
