# Generated by Django 5.0.14 on 2025-08-14 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationchannel_pushsubscription"),
        ("parties", "0004_watchparty_allow_public_search_and_more"),
        ("videos", "0003_videoprocessing_videostreamingurl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("notification_type", models.CharField(blank=True, max_length=50)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("total_read", models.PositiveIntegerField(default=0)),
                ("total_clicked", models.PositiveIntegerField(default=0)),
                ("in_app_sent", models.PositiveIntegerField(default=0)),
                ("email_sent", models.PositiveIntegerField(default=0)),
                ("push_sent", models.PositiveIntegerField(default=0)),
                ("sms_sent", models.PositiveIntegerField(default=0)),
                ("delivery_rate", models.FloatField(default=0.0)),
                ("read_rate", models.FloatField(default=0.0)),
                ("click_rate", models.FloatField(default=0.0)),
                ("avg_delivery_time_seconds", models.FloatField(default=0.0)),
                ("avg_read_time_minutes", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification_analytics",
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("html_content", models.TextField(blank=True)),
                ("target_criteria", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="notificationqueue",
            name="created_by",
        ),
        migrations.AlterModelOptions(
            name="notificationchannel",
            options={"ordering": ["delivery_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="notificationdelivery",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pushsubscription",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notificatio_status_ab0dcc_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notificatio_channel_169003_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notificatio_next_re_f74caa_idx",
        ),
        migrations.RemoveIndex(
            model_name="notificationdelivery",
            name="notificatio_created_fee8f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushsubscription",
            name="push_subscr_user_id_c81a15_idx",
        ),
        migrations.RemoveIndex(
            model_name="pushsubscription",
            name="push_subscr_platfor_832a78_idx",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="email_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="friend_requests",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="in_app_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="marketing",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="party_invites",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="party_updates",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="push_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="quiet_end_time",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="quiet_hours_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="quiet_start_time",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="sms_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="system_updates",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="video_uploads",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="error_code",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="failed_at",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="max_attempts",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="next_retry_at",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="provider_message_id",
        ),
        migrations.RemoveField(
            model_name="notificationdelivery",
            name="recipient_address",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="apns_token",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="device_name",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="fcm_token",
        ),
        migrations.RemoveField(
            model_name="pushsubscription",
            name="platform",
        ),
        migrations.AddField(
            model_name="notification",
            name="html_content",
            field=models.TextField(blank=True, verbose_name="Rich HTML Content"),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="send_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="send_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="send_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("in_app", "In-App Notification"),
                    ("email", "Email"),
                    ("push", "Push Notification"),
                    ("sms", "SMS"),
                    ("webhook", "Webhook"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="delivery_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="name",
            field=models.CharField(default="Default Channel", max_length=100),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="external_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="email_html_template",
            field=models.TextField(blank=True, verbose_name="Email HTML Template"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="html_template",
            field=models.TextField(blank=True, verbose_name="Rich HTML Template"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="push_body_template",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Push Body Template"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="push_title_template",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Push Title Template"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="send_email",
            field=models.BooleanField(
                default=False, verbose_name="Send Email by Default"
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="send_push",
            field=models.BooleanField(
                default=True, verbose_name="Send Push Notification by Default"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("dismissed", "Dismissed"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notificationchannel",
            ),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("party_invite", "Party Invitation"),
                    ("party_started", "Party Started"),
                    ("party_reminder", "Party Reminder"),
                    ("friend_request", "Friend Request"),
                    ("friend_accepted", "Friend Request Accepted"),
                    ("video_uploaded", "Video Uploaded"),
                    ("video_processed", "Video Processing Complete"),
                    ("comment_reply", "Comment Reply"),
                    ("system_update", "System Update"),
                    ("subscription_expiring", "Subscription Expiring"),
                    ("subscription_expired", "Subscription Expired"),
                    ("payment_success", "Payment Successful"),
                    ("payment_failed", "Payment Failed"),
                    ("account_security", "Account Security Alert"),
                    ("maintenance_notice", "Maintenance Notice"),
                    ("feature_announcement", "New Feature"),
                    ("community_update", "Community Update"),
                    ("weekly_digest", "Weekly Digest"),
                    ("content_recommendation", "Content Recommendation"),
                    ("achievement_unlocked", "Achievement Unlocked"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="auth_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="endpoint",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="last_used",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="p256dh_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pushsubscription",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "scheduled_at"], name="notificatio_status_2ea0f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_7ba7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification", "status"], name="notificatio_notific_131b46_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="notificationpreferences",
            table="user_notification_preferences",
        ),
        migrations.AddIndex(
            model_name="notificationanalytics",
            index=models.Index(fields=["-date"], name="notificatio_date_cc05c3_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationanalytics",
            index=models.Index(
                fields=["notification_type", "-date"],
                name="notificatio_notific_dbe4e6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationanalytics",
            unique_together={("date", "notification_type")},
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="target_users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.DeleteModel(
            name="NotificationQueue",
        ),
    ]
